### ISSUE TITLE
P value is same for  genes in FeatureCorr function

### ISSUE THREAD

**Issue by joachimsiaw** [DKundnani/FeatureCorr#1]
I used  the primefeature_corr function to calculate the the  correlation of a primefeaure (i.e geneA) with all other genes in tumor samples (n=709). I noticed that though all the genes have different correlation coefficients, they have the same p-value of 2.4e10-48. Is this not strange that all the genes (about 14000 genes)have the same p-values even for genes the have 0 correlation coefficient?

Is this a bug or what is the way to correct this?

**Comment by DKundnani** [comment]
Hi @joachimsiaw there was a bug in the code. It's corrected. You may try it again after installing it from GitHub again.
